name: Update DNS records

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "zonefiles/**.zone"

permissions:
  id-token: write
  contents: read

jobs:
  validate-zonefiles:
    uses: ./.github/workflows/pre-commit.yaml

  update-dns:
    needs:
      - validate-zonefiles
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install cli53
        run: |
          set -e
          mkdir -p $HOME/bin
          curl -LSsf -o $HOME/bin/cli53 https://github.com/barnybug/cli53/releases/download/$CLI53_RELEASE/cli53-linux-amd64
          chmod 755 $HOME/bin/cli53
        env:
          CLI53_RELEASE: "v0.9.0"

      - name: Update zones
        run: |
          set -e
          (
            git diff-tree --no-commit-id --diff-filter=ACRM --name-only -r HEAD^ HEAD -- '*.zone' ||
            git diff-tree --no-commit-id --diff-filter=ACRM --name-only -r --root HEAD -- '*.zone'
          ) | while read zonefile; do
            zone=${zonefile##*/}
            zone=${zone%.zone}
            $HOME/bin/cli53 import --replace -n --file $zonefile $zone &&
              $HOME/bin/cli53 import --replace --file $zonefile $zone
          done
