name: pre-commit

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install bind-utils
        run: |
          sudo apt-get update
          sudo apt-get -y install bind9-utils

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
